### ISSUE TITLE
Flask fails to install on setup.py

### ISSUE THREAD

**Issue by cheizer** [cmdmnt/commandment#12]
Error:
Installed /Users/local/Desktop/mdm/commandment/env/lib/python3.6/site-packages/Flask_REST_JSONAPI-0.13.2-py3.6.egg
error: The 'Flask' distribution was not found and is required by commandment, flask-marshmallow, Flask-OAuthlib

Changing "Flask" to "flask" in the setup.py install_requires fixes it.

**Comment by cheizer** [comment]
Also, changing the order is also needed. Move "flask" below "Flask-JWT". install_requires installs from the bottom up

**Comment by mosen** [comment]
hey there.
thanks for reporting this. I've been working out of requirements.txt so i'll update setup.py to reflect the latest dependencies.
