### ISSUE TITLE
Execute script on MacOS on push notification

### ISSUE THREAD

**Issue by aldegoeij** [cmdmnt/commandment#3]
Hello Jesse, does the current implementation allow me to send push notifications to MacOS devices to trigger a script/application to execute or reply? Or would I need to have an approved app in the app store to receive these push notifications?
Thanks!

**Comment by jessepeterson** [comment]
Sorry for the delay!

Yes, you can send an `InstallApplication` MDM command using commandment which can install an arbitrary Apple package. The caveat is that this pkg does need to be signed by a certificate the device trusts (which can be the MDM certificate). Apple packages can include scripts in their post/pre-install steps.

I hope that answers the question!
